### ISSUE TITLE
Downgrade engines.node to minimum required node version

### ISSUE THREAD

**Issue by jlegrone** [bahmutov/am-i-a-dependency#2]
## Description
Package authors may often want to run their tests against legacy node versions.  For example, [ember-cli targets node 4.5](https://github.com/ember-cli/ember-cli/blob/0d17e839ca7a5128d1b95b9981a7e77ed0e55ead/package.json#L147).

This package declares its node engine as v6, which causes builds to fail in earlier node versions when using yarn to install dependencies.

## Proposed Solution
Target node v4 or earlier. From a cursory first look, it doesn't look like you're using any apis that would require code changes or transpilation. 😄 

## Workaround
Using `yarn install --ignore-engines` prevents build errors, but this does forego desirable safety checks.

**Comment by bahmutov** [comment]
Version `1.1.1` has been published to NPM. The full release note can be found at [am-i-a-dependency/releases/tag/v1.1.1](https://github.com/bahmutov/am-i-a-dependency/releases/tag/v1.1.1).

**Tip:** safely upgrade dependency am-i-a-dependency in your project using [next-update](https://github.com/bahmutov/next-update)
